site_name: Polars H3
site_author: Sergey Filimonov
repo_url: "https://github.com/Filimoa/polars-h3"
repo_name: "polars-h3"
site_url: "https://filimoa.github.io/polars-h3/"
dev_addr: "localhost:8001"
theme:
  name: material
  variant: modern
  logo: assets/h3-logo.svg
  favicon: assets/h3-logo.svg
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.tabs.link
  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - User guide: guide.md
  - API Reference:
      - Overview: api-reference/index.md
      - Indexing: api-reference/indexing.md
      - Index inspection: api-reference/inspection.md
      - Hierarchy: api-reference/hierarchy.md
      - Directed edges: api-reference/edge.md
      - Traversal: api-reference/traversal.md
      - Vertices: api-reference/vertexes.md
      - Metrics: api-reference/metrics.md
      - Graphing: graphing.md

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Filimoa/polars-h3
      name: Polars H3 on GitHub

copyright: Copyright &copy; Sergey Filimonov
